### ISSUE TITLE
Java Heap Space Exception During Compilation

### ISSUE THREAD

**Issue by mohitgangrade** [athensresearch/athens#106]
**version** 

0.1.0-SNAPSHOT

**platform**

Windows 10
8 GB RAM
Chrome browser

**problem**

The project couldn't compile. It kept throwing this exception:

shadow-cljs - HTTP server available at http://localhost:3000
shadow-cljs - server version: 2.8.83 running at http://localhost:9630
shadow-cljs - nREPL server started on port 8777
shadow-cljs - watching build :app
[:app] Configuring build.
Exception in thread "async-thread-macro-1" java.lang.OutOfMemoryError: Java heap space
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetPublicMethods(Unknown Source)
        at java.lang.Class.privateGetPublicMethods(Unknown Source)
        at java.lang.Class.getMethods(Unknown Source)
        at clojure.lang.Reflector.getMethods(Reflector.java:498)
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:436)
        at shadow.cljs.devtools.server.fs_watch_jvm$poll_changes.invokeStatic(fs_watch_jvm.clj:17)
        at shadow.cljs.devtools.server.fs_watch_jvm$poll_changes.invoke(fs_watch_jvm.clj:16)
        at clojure.core$map$fn__5866.invoke(core.clj:2753)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$apply.invokeStatic(core.clj:660)
        at clojure.core$mapcat.invokeStatic(core.clj:2783)
        at clojure.core$mapcat.doInvoke(core.clj:2783)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at shadow.cljs.devtools.server.fs_watch_jvm$watch_loop.invokeStatic(fs_watch_jvm.clj:46)
        at shadow.cljs.devtools.server.fs_watch_jvm$watch_loop.invoke(fs_watch_jvm.clj:33)
        at shadow.cljs.devtools.server.fs_watch_jvm$start$fn__21310.invoke(fs_watch_jvm.clj:77)
        at clojure.core.async$thread_call$fn__7074.invoke(async.clj:484)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[:app] Compiling ...

[2020-05-30 15:20:18.695 - WARNING] :shadow.cljs.devtools.server.util/handle-ex - {:msg {:type :start-autobuild}}

OutOfMemoryError Java heap space

**repro**

I just did "lein dev"

**Comment by mohitgangrade** [comment]
I solved the problem for now by adding this like to project.clj:

:jvm-opts ["-Xmx1G"] ;; 1 GB

**Comment by avichalp** [comment]
Welcome to Athens! Glad you figured it out. What is your JDK version?  

There was another OOM issue on windows: #23 

Maybe we should add that flag to `project.clj` if it is a problem for windows users.
