### ISSUE TITLE
RTC cannot synchronize Chinese content and report an error

### ISSUE THREAD

**Issue by gnuwind** [athensresearch/athens#1602]
**Problem**
RTC cannot synchronize Chinese content and report an error. I tried to connect to the local LAN party using 2 local clients. When I type in English or a number, the two clients synchronize normally. When I typed Chinese, I couldn't sync (on the client where I typed it, hitting enter didn't even get to a new line, it looked like it was blocked), and the LAN Party server reported an error. You can try this: 雅典 (Athens in Chinese). 
Based on the error message of the lan party server, the problem may be related to the encoding/processing of UTF-8.

**Screenshots/Demo**
```
2021-08-29T01:56:07.204Z D-N2 DEBUG [datahike.connector:78] - Transacting with arguments:  {:tx-data [{:block/uid "08-29-2021", :block/children ({:db/id -1, :block/uid "768f2ced5", :block/string "", :block/order 13, :block/open true})}]}
Prod 09:56:07.343 [worker-3] INFO  athens.self-hosted.web.datascript - Transacted event-id: #uuid "eb20c54e-3e60-4a85-87b6-5c2f86581ad8" , tx-id: 536870964
Sun Aug 29 09:56:14 CST 2021 [worker-4] ERROR - handle websocket frame org.httpkit.server.Frame$TextFrame@55e1e739
java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xd0
 at [Source: (ByteArrayInputStream); line: 1, column: 185]
        at com.cognitect.transit.impl.ReaderFactory$ReaderImpl.read(ReaderFactory.java:114)
        at cognitect.transit$read.invokeStatic(transit.clj:319)
        at cognitect.transit$read.invoke(transit.clj:315)
        at athens.self_hosted.clients$_LT__transit.invokeStatic(clients.clj:40)
        at athens.self_hosted.clients$_LT__transit.invoke(clients.clj:36)
        at athens.self_hosted.components.web$make_receive_handler$receive_handler__32451.invoke(web.clj:69)
        at clojure.core$partial$fn__5857.invoke(core.clj:2628)
        at org.httpkit.server.AsyncChannel.messageReceived(AsyncChannel.java:153)
        at org.httpkit.server.WSHandler.run(RingHandler.java:183)
        at org.httpkit.server.LinkingRunnable.run(RingHandler.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xd0
 at [Source: (ByteArrayInputStream); line: 1, column: 185]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3610)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3617)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeUtf8_2(UTF8StreamJsonParser.java:3390)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2519)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2471)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:302)
        at com.cognitect.transit.impl.JsonParser.parseVal(JsonParser.java:60)
        at com.cognitect.transit.impl.JsonParser.parseMap(JsonParser.java:112)
        at com.cognitect.transit.impl.JsonParser.parseArray(JsonParser.java:128)
        at com.cognitect.transit.impl.JsonParser.parseVal(JsonParser.java:56)
        at com.cognitect.transit.impl.JsonParser.parseMap(JsonParser.java:112)
        at com.cognitect.transit.impl.JsonParser.parseArray(JsonParser.java:128)
        at com.cognitect.transit.impl.JsonParser.parseVal(JsonParser.java:56)
        at com.cognitect.transit.impl.JsonParser.parse(JsonParser.java:46)
        at com.cognitect.transit.impl.ReaderFactory$ReaderImpl.read(ReaderFactory.java:112)
        ... 14 more
```
**Athens Version**
1.0.0-ALPHA.RTC.2
OS: Win10

**Comment by gnuwind** [comment]
If I start LAN Party in my Linux, Chinese content can be synchronized, and my Linux default LANG is UTF-8.
So I tried adding the encoding parameter when starting the jar in Win10, and it seems that this problem can be solved.
`java -Dfile.encoding=UTF-8 -jar athens-lan-party-standalone.jar`
