### ISSUE TITLE
Says Update Available, then freezes

### ISSUE THREAD

**Issue by RhvdG** [athensresearch/athens#695]
**Problem**
It says Update Available, when I click Update it shows blank screen, nothing else happens until I close the window, then it says Javascript error:

`Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
at Object.athens$main$core$send_status_to_window [as send_status_to_window] (/Applications/Athens.app/Contents/Resources/app.asar/.shadow-cljs/builds/main/dev/out/cljs-runtime/athens.main.core.js:20:53)
at MacUpdater.<anonymous> (/Applications/Athens.app/Contents/Resources/app.asar/.shadow-cljs/builds/main/dev/out/cljs-runtime/athens.main.core.js:67:25)
at MacUpdater.emit (events.js:223:5)
at ProgressCallbackTransform.downloadOptions.onProgress (/Applications/Athens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:704:47)
at ProgressCallbackTransform._transform (/Applications/Athens.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/ProgressCallbackTransform.js:44:14)
at ProgressCallbackTransform.Transform._read (_stream_transform.js:189:10)
at ProgressCallbackTransform.Transform._write (_stream_transform.js:177:12)
at doWrite (_stream_writable.js:435:12)
at writeOrBuffer (_stream_writable.js:419:5)
at ProgressCallbackTransform.Writable.write (_stream_writable.js:309:11)`

**Screenshots/Demo**

**Athens Version**
beta 42

**Comment by Positron010** [comment]
I have the same issue on Mac OS Big Sur.

**Comment by tangjeff0** [comment]
Not sure why this happens, but I can say this is happening around https://github.com/athensresearch/athens/blob/423d6540ac7ace6dcdbed8b1dd8c11cbf6556b63/src/cljs/athens/main/core.cljs#L18-L25

This means that `@main-window` is null, thus accessing `webContents` throws an error.

A solution that might work would be making sure `send-status-to-window` checks that `@main-window` is not null before sending.

But I don't know why it is null. It could be that `send-status-to-window` is called before `initWindow` is called, such that `main-window` is not `reset` with a valid value.

**Comment by Positron010** [comment]
Hi,
Could you kindly release another binary of the application, with the fix, for the non-developers out-there -like me :) @tangjeff0

**Comment by tangjeff0** [comment]
Release coming today @Positron010

**Comment by tangjeff0** [comment]
You may have to download the latest version directly at https://athens-apps.s3.us-east-2.amazonaws.com/Athens-1.0.0-beta.46.dmg @Positron010 @RhvdG  @androswong418

**Comment by Positron010** [comment]
Thanks for your hard work @tangjeff0 ! It didn't ask for updates, but I hope the issue has been solved. The OpenCollective e-mail not being detected still persists though.

**Comment by tangjeff0** [comment]
It didn't ask for updates because it's the latest, newest version! More people are having the Open Collective issue, thank you.
