### ISSUE TITLE
Hangs on startup with ENOENT

### ISSUE THREAD

**Issue by sidmani** [athensresearch/athens#916]
**Problem**
Athens hangs on startup and just displays a white screen.

**Screenshots/Demo**
If I launch from a shell, I get the following trace:
```
no "source-map-support" (run "npm install source-map-support --save-dev" to get it)
09:49:03.798 › Athens starting... version=1.0.0-beta.65
09:49:03.854 › Checking for update
09:49:03.855 › Checking for update...
09:49:03.954 › Error: Error: ENOENT, dev-app-update.yml not found in /usr/lib/athens.asar
    at createError (electron/js2c/asar_bundle.js:5:1289)
    at e.readFile (electron/js2c/asar_bundle.js:5:8076)
    at go$readFile (/usr/lib/athens.asar/node_modules/graceful-fs/graceful-fs.js:110:14)
    at readFile (/usr/lib/athens.asar/node_modules/graceful-fs/graceful-fs.js:107:12)
    at /usr/lib/athens.asar/node_modules/electron-updater/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at readFile (/usr/lib/athens.asar/node_modules/electron-updater/node_modules/universalify/index.js:7:14)
    at AppImageUpdater.loadUpdateConfig (/usr/lib/athens.asar/node_modules/electron-updater/out/AppUpdater.js:602:67)
    at Lazy.<anonymous> (/usr/lib/athens.asar/node_modules/electron-updater/out/AppUpdater.js:211:58)
    at Lazy.get value [as value] (/usr/lib/athens.asar/node_modules/lazy-val/out/main.js:23:25)
09:49:03.955 › Error in auto-updater. Error: ENOENT, dev-app-update.yml not found in /usr/lib/athens.asar
(node:180702) UnhandledPromiseRejectionWarning: Error: ENOENT, dev-app-update.yml not found in /usr/lib/athens.asar
    at createError (electron/js2c/asar_bundle.js:5:1289)
    at e.readFile (electron/js2c/asar_bundle.js:5:8076)
    at go$readFile (/usr/lib/athens.asar/node_modules/graceful-fs/graceful-fs.js:110:14)
    at readFile (/usr/lib/athens.asar/node_modules/graceful-fs/graceful-fs.js:107:12)
    at /usr/lib/athens.asar/node_modules/electron-updater/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at readFile (/usr/lib/athens.asar/node_modules/electron-updater/node_modules/universalify/index.js:7:14)
    at AppImageUpdater.loadUpdateConfig (/usr/lib/athens.asar/node_modules/electron-updater/out/AppUpdater.js:602:67)
    at Lazy.<anonymous> (/usr/lib/athens.asar/node_modules/electron-updater/out/AppUpdater.js:211:58)
    at Lazy.get value [as value] (/usr/lib/athens.asar/node_modules/lazy-val/out/main.js:23:25)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:180702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:180702) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Athens Version**
1.0.0-beta65, although this happened before I updated from beta 61 as well. I'm on arch linux, kernel version 5.11.10-arch1-1.

**Comment by sid597** [comment]
@sidmani This does not happen in ~latest versions, if it does for you please reopen this issue.

**Comment by homunkoloss** [comment]
@sid597  I am having this problem after my last update on the newest release
```
~ athens
no "source-map-support" (run "npm install source-map-support --save-dev" to get it)
08:38:29.834 › Athens starting... version=1.0.0-beta.96
08:38:29.942 › Checking for update
08:38:29.944 › Checking for update...
(node:1607580) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `electron --trace-warnings ...` to show where the warning was created)
libva error: /usr/lib/dri/iHD_drv_video.so init failed
08:38:29.947 › Error: Error: ENOENT, dev-app-update.yml not found in /usr/lib/athens.asar
    at createError (electron/js2c/asar_bundle.js:5:1289)
    at fsReadFileAsar (electron/js2c/asar_bundle.js:5:7482)
    at e.readFile (electron/js2c/asar_bundle.js:5:8550)
    at go$readFile (/usr/lib/athens.asar/node_modules/graceful-fs/graceful-fs.js:118:14)
    at Object.readFile (/usr/lib/athens.asar/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /usr/lib/athens.asar/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.readFile (/usr/lib/athens.asar/node_modules/universalify/index.js:7:14)
    at AppImageUpdater.loadUpdateConfig (/usr/lib/athens.asar/node_modules/electron-updater/out/AppUpdater.js:379:48)
    at Lazy.<anonymous> (/usr/lib/athens.asar/node_modules/electron-updater/out/AppUpdater.js:65:60)
08:38:29.948 › Error in auto-updater. Error: ENOENT, dev-app-update.yml not found in /usr/lib/athens.asar
(node:1607580) UnhandledPromiseRejectionWarning: Error: ENOENT, dev-app-update.yml not found in /usr/lib/athens.asar
    at createError (electron/js2c/asar_bundle.js:5:1289)
    at fsReadFileAsar (electron/js2c/asar_bundle.js:5:7482)
    at e.readFile (electron/js2c/asar_bundle.js:5:8550)
    at go$readFile (/usr/lib/athens.asar/node_modules/graceful-fs/graceful-fs.js:118:14)
    at Object.readFile (/usr/lib/athens.asar/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /usr/lib/athens.asar/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.readFile (/usr/lib/athens.asar/node_modules/universalify/index.js:7:14)
    at AppImageUpdater.loadUpdateConfig (/usr/lib/athens.asar/node_modules/electron-updater/out/AppUpdater.js:379:48)
    at Lazy.<anonymous> (/usr/lib/athens.asar/node_modules/electron-updater/out/AppUpdater.js:65:60)
(node:1607580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1607580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1607613:0912/083829.953206:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Electron Version is 14.0.0-1

**Comment by homunkoloss** [comment]
Downgrading to electron 13.2.3-1 fixes the issue for me.

**Comment by martin-braun** [comment]
I have the same problem on MacOS:

```
00:10:52.597 › Athens starting... version=2.0.0-beta.24
00:10:52.824 › Checking for update
00:10:52.825 › Checking for update...
00:10:53.232 › Error: Error: ENOENT: no such file or directory, open '/Users/marty/Projects/martin-braun/athens/dev-app-update.yml'
00:10:53.233 › Error in auto-updater. Error: ENOENT: no such file or directory, open '/Users/marty/Projects/martin-braun/athens/dev-app-update.yml'
(node:86837) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/marty/Projects/martin-braun/athens/dev-app-update.yml'
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:86837) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:86837) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
shadow-cljs - #5 ready!
```

This electron-builder is a mess in dev mode and it should be documented @sid597.

The solution is to create the `dev-app-update.yml`: 

> Maybe this will help someone for solving this issue. For me it worked creating the `dev-app-update.yml` manually  in the top level of my electron app. I am using the two package.json way.
> 
> My directory structure then looks like this
> 
> ```
> .
> ├── app
> │   ├── main
> │   │   ├── main.js
> │   │   └── update.js
> │   ├── package.json
> │   ├── renderer
> │   │   ├── ...
> │   │       └── main.jsx
> │   └── yarn.lock
> ├── dev-app-update.yml
> ├── package.json
> ├── publish.sh
> └── yarn.lock
> ```
> 
> And in `dev-app-update.yml` I inserted the following for using GitHub:
> 
> ```
> owner: yourGHName
> repo: yourGHRepoName
> provider: github
> ```
> 
> And then normally start your main entry file with `electron main.js`.

_Originally posted by @alexanderwe in https://github.com/electron-userland/electron-builder/issues/1505#issuecomment-318330077_

So for my fork I created the `dev-app-update.yml` like this: 

```yml
owner: martin-braun
repo: athens
provider: github
```

Then the build runs, but it want's to download an update: 

```
Error in auto-updater. HttpError: 404 
"method: GET url: https://github.com/martin-braun/athens/releases/download/v2.0.0-beta.24/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
```

@sid597 This is messed up to me and it's not documented. Why is the auto-updater even attempting to update on a dev build, please? Can this be re-opened please?
